package br.com.fateczl.apihae.domain.enums;

public enum DimensaoHae {
    DIMENSAO_1_DIDATICO_PEDAGOGICO,
    DIMENSAO_2_LABORATORIOS_ENSINO_E_EQUIPAMENTOS,
    DIMENSAO_3_PESQUISA_E_EXTENSAO_EQUIPAMENTOS_E_LABORATORIOS,
    DIMENSAO_4_ATIVIDADES_FORMATIVAS,
    DIMENSAO_5_INFRAESTRUTURA,
    DIMENSAO_6_DESENVOLVIMENTO_DE_PESSOAS,
    DIMENSAO_7_CONVENIOS_E_PARCEIRAS_INSTITUCIONAIS,
    DIMENSAO_8_IMPLANTACAO_DE_CURSOS,
    DIMENSAO_9_GESTAO_DA_ROTINA
}
